-- MySQL Script generated by MySQL Workbench
-- Sun Mar  3 17:57:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbagendaelectronica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbagendaelectronica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbagendaelectronica` DEFAULT CHARACTER SET utf8 ;
USE `dbagendaelectronica` ;

-- -----------------------------------------------------
-- Table `dbagendaelectronica`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbagendaelectronica`.`evento` (
  `idevento` INT(11) NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(45) NULL DEFAULT NULL,
  `duracion` VARCHAR(40) NULL DEFAULT NULL,
  `locacion` VARCHAR(500) NULL DEFAULT NULL,
  `fechainicio` DATETIME NULL DEFAULT NULL,
  `fechafin` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idevento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `dbagendaelectronica`.`instituciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbagendaelectronica`.`instituciones` (
  `idinstituciones` INT(11) NOT NULL AUTO_INCREMENT,
  `rif` VARCHAR(45) NULL DEFAULT NULL,
  `nombeinstitucion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(500) NULL DEFAULT NULL,
  `correo` VARCHAR(250) NULL DEFAULT NULL,
  `personacontacto` VARCHAR(100) NULL DEFAULT NULL,
  `telefonopersona` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idinstituciones`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `dbagendaelectronica`.`detalleeventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbagendaelectronica`.`detalleeventos` (
  `iddetalleeventos` INT(11) NOT NULL AUTO_INCREMENT,
  `instituciones_idinstituciones` INT(11) NOT NULL,
  `evento_idevento` INT(11) NOT NULL,
  PRIMARY KEY (`iddetalleeventos`, `instituciones_idinstituciones`, `evento_idevento`),
  INDEX `fk_DETALLEEVENTOS_INSTITUCIONES1_idx` (`instituciones_idinstituciones` ASC),
  INDEX `fk_DETALLEEVENTOS_EVENTO1_idx` (`evento_idevento` ASC) ,
  CONSTRAINT `fk_DETALLEEVENTOS_EVENTO1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `dbagendaelectronica`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLEEVENTOS_INSTITUCIONES1`
    FOREIGN KEY (`instituciones_idinstituciones`)
    REFERENCES `dbagendaelectronica`.`instituciones` (`idinstituciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `dbagendaelectronica`.`facilitadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbagendaelectronica`.`facilitadores` (
  `idfacilitadores` INT(11) NOT NULL AUTO_INCREMENT,
  `iddocumento` VARCHAR(45) NULL DEFAULT NULL,
  `nombres` VARCHAR(250) NULL DEFAULT NULL,
  `apellidos` VARCHAR(250) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`idfacilitadores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `dbagendaelectronica`.`detallefacilitador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbagendaelectronica`.`detallefacilitador` (
  `iddetallefacilitador` INT(11) NOT NULL AUTO_INCREMENT,
  `evento_idevento` INT(11) NOT NULL,
  `facilitadores_idfacilitadores` INT(11) NOT NULL,
  PRIMARY KEY (`iddetallefacilitador`, `evento_idevento`, `facilitadores_idfacilitadores`),
  INDEX `fk_DETALLEFACILITADOR_EVENTO_idx` (`evento_idevento` ASC),
  INDEX `fk_DETALLEFACILITADOR_FACILITADORES1_idx` (`facilitadores_idfacilitadores` ASC) ,
  CONSTRAINT `fk_DETALLEFACILITADOR_EVENTO`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `dbagendaelectronica`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLEFACILITADOR_FACILITADORES1`
    FOREIGN KEY (`facilitadores_idfacilitadores`)
    REFERENCES `dbagendaelectronica`.`facilitadores` (`idfacilitadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `dbagendaelectronica`.`participantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbagendaelectronica`.`participantes` (
  `idparticipante` INT(11) NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(150) NULL DEFAULT NULL,
  `apellidos` VARCHAR(150) NULL DEFAULT NULL,
  `iddocumento` VARCHAR(45) NULL DEFAULT NULL,
  `edad` INT(11) NULL DEFAULT NULL,
  `curso` VARCHAR(45) NULL DEFAULT NULL,
  `seccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`idparticipante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `dbagendaelectronica`.`detalleparticipantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbagendaelectronica`.`detalleparticipantes` (
  `iddetalleparticipantes` INT(11) NOT NULL AUTO_INCREMENT,
  `evento_idevento` INT(11) NOT NULL,
  `participantes_idparticipante` INT(11) NOT NULL,
  PRIMARY KEY (`iddetalleparticipantes`, `evento_idevento`, `participantes_idparticipante`),
  INDEX `fk_DETALLEPARTICIPANTES_EVENTO1_idx` (`evento_idevento` ASC) ,
  INDEX `fk_DETALLEPARTICIPANTES_PARTICIPANTES1_idx` (`participantes_idparticipante` ASC) ,
  CONSTRAINT `fk_DETALLEPARTICIPANTES_EVENTO1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `dbagendaelectronica`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLEPARTICIPANTES_PARTICIPANTES1`
    FOREIGN KEY (`participantes_idparticipante`)
    REFERENCES `dbagendaelectronica`.`participantes` (`idparticipante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `dbagendaelectronica`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbagendaelectronica`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
